using System.Numerics;
using Content.Client.Humanoid;
using Content.Client.Message;
using Content.Client.UserInterface.Controls;
using Content.Shared._ADT.CharecterFlavor;
using Content.Shared.Humanoid;
using Content.Shared.Inventory; // Xenon-edit
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface; // Xenon-edit
using Robust.Client.UserInterface.Controls; // Xenon-edit
using Robust.Client.UserInterface.XAML;
using static Robust.Client.UserInterface.Controls.BoxContainer; // Xenon-edit
using Robust.Shared.Prototypes;

namespace Content.Client._ADT.CharecterFlavor;

[GenerateTypedNameReferences]
public sealed partial class CharacterFlavorWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly IPrototypeManager _proto = default!;
    [Dependency] private readonly IClyde _clyde = default!;

    /// <summary>
    /// true, если окно открыто как предпросмотр из лобби (без серверной загрузки headshot).
    /// </summary>
    public bool IsPreviewMode { get; set; }

    public CharacterFlavorWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        HeadshotLoadingLabel.SetMarkup(Loc.GetString("headshot-loading"));
    }

    public void SetEntity(EntityUid uid)
    {
        if (!_entityManager.TryGetComponent<CharacterFlavorComponent>(uid, out var flavor))
            return;

        if (!_entityManager.TryGetComponent<MetaDataComponent>(uid, out var metaData))
            return;

        if (flavor.HeadshotUrl != string.Empty)
        {
            HeadshotImage.TexturePath = "/Textures/_White/Interface/headshot-loading.png";
            HeadshotLoadingLabel.Visible = true;
            HeadshotContainer.Visible = true;
        }
        else
        {
            HeadshotContainer.Visible = false;
        }

        Title = metaData.EntityName;
        FlavorTextLabel.SetMarkup(flavor.FlavorText);
        PopulateItemsList(uid); // Xenon-edit
    }

    public void SetHeadshot(byte[] image)
    {
        var headshot = HeadshotTextureCache.GetOrLoadTexture(image, _clyde);

        if (headshot != null)
        {
            HeadshotImage.Texture = headshot;
            HeadshotImage.ModulateSelfOverride = null;
            HeadshotLoadingLabel.Visible = false;
            HeadshotContainer.Visible = true;
        }
        else
            HeadshotContainer.Visible = false;
    }

    // Xenon-edit start
    private void PopulateItemsList(EntityUid uid)
    {
        ItemsContainer.RemoveAllChildren();

        if (!_entityManager.TryGetComponent<InventoryComponent>(uid, out var inv))
            return;

        var invSystem = _entityManager.System<InventorySystem>();
        var enumerator = invSystem.GetSlotEnumerator((uid, inv), SlotFlags.WITHOUT_POCKET);

        while (enumerator.NextItem(out var item, out var slotDef))
        {
            var name = _entityManager.GetComponent<MetaDataComponent>(item).EntityName;

            var row = new BoxContainer
            {
                Orientation = LayoutOrientation.Horizontal,
                SeparationOverride = 4,
                Margin = new Thickness(4, 0)
            };

            var sprite = new SpriteView
            {
                OverrideDirection = Direction.South,
                SetSize = new Vector2(32, 32),
                Stretch = SpriteView.StretchMode.Fill
            };
            sprite.SetEntity(item);
            row.AddChild(sprite);

            var label = new Label
            {
                Text = name,
                VerticalAlignment = VAlignment.Center,
                HorizontalExpand = true,
                ClipText = true
            };
            row.AddChild(label);

            ItemsContainer.AddChild(row);
        }
    }
    // Xenon-edit end
}
