using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;
using Robust.Shared.Utility;

namespace Content.Client.FlavorText;

[GenerateTypedNameReferences]
public sealed partial class FlavorText : Control
{
    public Action<string>? OnFlavorTextChanged;
    public Action<string>? OnHeadshotUrlChanged;
    public Action? OnPreviewRequested;

    public FlavorText()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        var loc = IoCManager.Resolve<ILocalizationManager>();
        CFlavorTextInput.Placeholder = new Rope.Leaf(loc.GetString("flavor-text-placeholder"));

        CFlavorTextInput.OnTextChanged += _ => FlavorTextChanged();
        CHeadshotUrlInput.OnTextChanged += _ => HeadshotUrlChanged();
        PreviewButton.OnPressed += _ => PreviewRequested();
    }

    public void FlavorTextChanged()
    {
        OnFlavorTextChanged?.Invoke(Rope.Collapse(CFlavorTextInput.TextRope).Trim());
    }

    public void HeadshotUrlChanged()
    {
        OnHeadshotUrlChanged?.Invoke(CHeadshotUrlInput.Text.Trim());
    }

    private void PreviewRequested()
    {
        OnPreviewRequested?.Invoke();
    }
}
