using Content.Client._ADT.UserInterface.Controls.FancyButton;
using Content.Client.Message;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;

namespace Content.Client._ADT.VendingMachines.UI;

[GenerateTypedNameReferences]
public sealed partial class FancyVendingMachineItem : BoxContainer
{
    public Action? BuyPressed;

    public FancyVendingMachineItem(EntProtoId entProto, string text, int count, int price)
    {
        RobustXamlLoader.Load(this);

        BuyButton.OnPressed += _ => BuyPressed?.Invoke();

        BuyButton.Disabled = count <= 0;

        ItemPrototype.SetPrototype(entProto);

        NameLabel.SetMarkup(text);

        var countColor = count > 0 ? "[color=white]" : "[color=red]";
        CountLabel.SetMarkup(Loc.GetString("vending-machine-ui-count", ("color", countColor), ("count", count)));

        var priceText = price <= 0
            ? Loc.GetString("vending-machine-ui-price-free")
            : Loc.GetString("vending-machine-ui-price", ("price", price));
        CostLabel.SetMarkup(priceText);
    }

    public void SetColoring(Color baseColor, Color border, Color hover, Color disabled)
    {
        BuyButton.Color = baseColor;
        BuyButton.BorderColor = border;
        BuyButton.HoveredColor = hover;
        BuyButton.DisabledColor = disabled;
        BuyButton.UpdateColor();
    }
}
