using System.Linq;
using Content.Shared._ADT.Economy;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._ADT.Economy.UI;

[GenerateTypedNameReferences]
public sealed partial class AtmWindow : DefaultWindow
{
    public Action<BoundUserInterfaceMessage>? OnWithdrawAttempt;

    private bool _hasCard;
    private int _balance;

    public AtmWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        WithdrawButton.OnPressed += _ =>
        {
            if (!int.TryParse(AmountLineEdit.Text.Trim(), out var amount) || amount <= 0)
                return;

            var pinText = PinLineEdit.Text.Trim();
            if (pinText.Length != 4 || !int.TryParse(pinText, out var pin))
                return;

            OnWithdrawAttempt?.Invoke(new ATMRequestWithdrawMessage(amount, pin));
        };

        PinLineEdit.OnTextChanged += _ =>
        {
            var text = PinLineEdit.Text;
            var filtered = new string(text.Where(char.IsDigit).ToArray());
            if (filtered.Length > 4)
                filtered = filtered[..4];
            PinLineEdit.Text = filtered;
        };

        AmountLineEdit.OnTextChanged += _ =>
        {
            var text = AmountLineEdit.Text;
            var filtered = new string(text.Where(char.IsDigit).ToArray());
            AmountLineEdit.Text = filtered;
        };
    }

    public void UpdateState(BoundUserInterfaceState state)
    {
        if (state is not ATMBuiState atmState)
            return;

        _hasCard = atmState.HasCard;
        _balance = atmState.AccountBalance;

        BalanceLabel.Text = Loc.GetString("atm-ui-balance", ("balance", _balance));
        BalanceLabel.Visible = _hasCard;

        StatusLabel.Text = atmState.InfoMessage;

        AmountLineEdit.Visible = _hasCard;
        Divider.Visible = _hasCard;
        PinLineEdit.Visible = _hasCard;
        WithdrawButton.Visible = _hasCard;
    }
}
